name: Bug Report
description: Report an issue about using Bazaar
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you are reporting a crash with the flatpak version please follow https://docs.flatpak.org/en/latest/debugging.html
      placeholder: Tell us what happened!
      value: "When I entered 2 + 2, I got the answer 6."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: Operating system (and desktop environment)
      placeholder: <os> <version>, <desktop> <version>
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Output of `flatpak info io.github.kolunmi.Bazaar`. If you are on Bazzite please run `rpm -qi bazaar`
      description: Please check the current version of Bazaar (Main Window > About Bazaar) so we can more easily indentify issues.
      render: shell
    validations:
      required: true

  - type: textarea
    id: extra-context
    attributes:
      label: Extra information or context
      description: Add any other context about the problem here.

