FROM ubuntu:25.10

RUN userdel -f -r ubuntu

RUN apt-get update && apt-get install -y \
    appstream \
    bash-completion \
    build-essential \
    cmake \
    gettext \
    git \
    libadwaita-1-dev \
    libdex-dev \
    libflatpak-dev \
    libglycin-2-dev \
    libglycin-gtk4-2-dev \
    libgtk-4-dev \
    liblcms2-dev \
    libxmlb-dev \
    libyaml-dev \
    libsoup-3.0-dev \
    libjson-glib-dev \
    libmd4c-dev \
    meson \
    ninja-build
