FROM fedora:rawhide

RUN dnf update -y && dnf install -y \
    meson \
    ninja \
    cmake \
    just \
    git \
    blueprint-compiler \
    desktop-file-utils \
    gtk4-devel \
    libadwaita-devel \
    libdex-devel \
    flatpak-devel \
    libxmlb-devel \
    appstream-devel \
    glycin-devel \
    glycin-gtk4-devel \
    libyaml-devel \
    libsoup3-devel \
    json-glib-devel \
    md4c-devel \
    webkitgtk6.0-devel \
    libsecret-devel \
    libproxy-devel \
    clangd
