name: Build Flatpak and Upload Artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_flatpak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Check Just Syntax
        shell: bash
        run: |
          just check

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt update
          sudo apt install -y flatpak-builder flatpak
          # Enable unprivileged user namespaces so that CI can work
          sudo aa-teardown >/dev/null 2>&1 || true

      - name: Build Flatpak
        id: build-flatpak
        shell: bash
        run: |
          CI=1 just build-flatpak
          just build-flatpak-bundle

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: io.github.kolunmi.Bazaar
          path: io.github.kolunmi.Bazaar.flatpak
          retention-days: 14

      - name: Display success message
        run: echo "Flatpak build and artifact upload complete!"
