on:
  push:
    branches: [master]
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/*"
      - "screenshots/*"
      - "translators.sh"
      - ".github/ISSUE_TEMPLATE/**"

name: CI Build Flatpak
jobs:

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Bazaar.flatpak
        manifest-path: build-aux/flatpak/io.github.kolunmi.Bazaar.json
        cache-key: flatpak-builder-${{ github.sha }}