on:
  push:
    branches: [master]
  pull_request:
name: CI Build Flatpak
jobs:

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Bazaar.flatpak
        manifest-path: build-aux/flatpak/io.github.kolunmi.Bazaar.json
        cache-key: flatpak-builder-${{ github.sha }}